### ISSUE TITLE
Konfiguration af søgeressourcer

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geosearch#16]
Tillad brugeren at vælge mellem søgeressourcer i konfigurationsdialogen.

Det kunne være en liste med flueben, så brugeren feks kunne fjerne hakket i "matrikel", hvis søgning i matrikler er irrelevant.

En sidegevinst ved at fjerne irrelevante ressourcer er, at svaret alt andet lige vil komme hurtigere.

**Comment by baffioso** [comment]
Er det muligt at lave det således, at man vinger af når man gerne vil lave matrikelsøgning, så pluginnet kun lister matrikler i dropdown? Alternativt kunne det laves sådan, at hvis brugeren starter med tal i søgningen, så ved geosearch at den skal starte med at liste matrikler.

Ballerup Kommune

**Comment by AsgerPetersen** [comment]
@baffioso jeg spekulerer på, om det ville passe i jeres use case, hvis man skal ind i konfigurations-dialogen (Altså klikke `Plugins`->`Geoserver DK`->`Settings`), når man ønsker at ændre søgeressourcer?

Har du overvejet, om #2 er vej, vi kan gå?

**Comment by ClockEnd** [comment]
Den bedste løsning for brugerne ville være at søgning på begyndt med et tal, altid er en matrikelsøgning

**Comment by AsgerPetersen** [comment]
Det svære er, at vi skal passe på ikke at lave funktionalitet, der forstyrrer i andre use cases. Nogle bruger feks geosearch til at søge postnumre. Man kan vel også forestille sig, at nogen kan finde på at søge adresse med husnummer først.

Kunne det være en idé, at brugeren i konfigurationen kan indstille
* Hvilke søgeressourcer (adresse, matrikel, politikreds, ....), der søges i
* Hvilken **rækkefølge** resultaterne leveres i
Med denne konfiguration, kan dem, der søger i matrikler sørge for at disse resultater altid står øverst. Og hvis man KUN søger i  matrikler, at der ikke er andre resultater.

**Comment by ClockEnd** [comment]
Det lyder bestemt som en farbar vej - havde lige overset postnumrene...

**Comment by ClockEnd** [comment]
har du et overslag over hvor meget det vil komme til at koste at få lavet sådan en konfiguration?

**Comment by AsgerPetersen** [comment]
Skudt fra hoften, så gætter jeg på 3-5 timer.

**Comment by baffioso** [comment]
Jeg sidder sammen med @ClockEnd og vi tænker at nogle brugere vil synes det er bøvlet at skulle ind i konfigurationen, hver gang de skal lave en matrikelsøgning. Så er #2 nok nemmere eller en boks, hvor man kan krydse af inden søgningen laves (går lidt i mod den simple UI). Synes stadig det skal være muligt at sætte søgeressourcer i konfigurations-dialogen.

**Comment by AsgerPetersen** [comment]
Enig. Det er for bøvlet, hvis det skal være en del af søgeprocessen.

Det giver god mening at kunne slå helt irrelevante søgeressourcer (feks politikredse) fra - en gang for alle. Men det er ikke denne funktionalitet, der skal sørge for at det mest relevante står øverst.

Jeg er ikke super interesseret i gøre brugergrænsefladen meget mere kompliceret.

Lige nu tænker jeg i to ændringer:
  1. Tillad brugeren at søge i kun een ressource ved at angive ressourcen i søgestrengen a la `mat: farum 16a`. Dette ville kun returnere matrikelresultater. Denne feature vil ikke få indflydelse for andre end dem, der har brug for den. Dem, der bruger Geosearch ofte, vil til gengæld hurtigt kunne lære konventionen.
  2. En eller anden form for efterprocessering af søgeresultatet fra Kortforsyningen, som sorterer resultatet efter match-grad i forhold til søgeteksten.

Vi har i øvrigt præcis samme diskussion offline med en fra en forsyningsvirksomhed i jeres nabolag. Der kunne være mulighed for noget fælles indsats.

**Comment by baffioso** [comment]
Vi tænker at `mat: farum 16a` er en god løsning. Så er det måske ikke så interessant at kunne indstille søgeressourcen, da filtrering kommer i søgningen. 

Kan du oplyse navnet på forsyningsvirksomhed, så vi kan gribe fat i dem?

**Comment by AsgerPetersen** [comment]
Jeg har givet kontaktoplysningerne på @ClockEnd videre.

**Comment by ClockEnd** [comment]
Vi er i kontakt..

**Comment by AsgerPetersen** [comment]
'mat: farum 16a'-ideen  er beskrevet i #2. Lad os diskutere den derovre.

**Comment by baffioso** [comment]
Tjek

**Comment by ClockEnd** [comment]
modtaget

**Comment by baffioso** [comment]
Denne kan vel godt lukkes nu

**Comment by ClockEnd** [comment]
Yep
Den 29/01/2016 22.54 skrev "Anders Barfod" <notifications@github.com>:
