### ISSUE TITLE
Nemmere matrikelsøgning

### ISSUE THREAD

**Issue by baffioso** [Septima/qgis-geosearch#18]
Er det muligt at lave det således, at man vinger af når man gerne vil lave matrikelsøgning, så pluginnet kun lister matrikler i dropdown? Alternativt kunne det laves sådan, at hvis brugeren starter med tal i søgningen, så ved geosearch at den skal starte med at liste matrikler. 

Ballerup Kommune

**Comment by AsgerPetersen** [comment]
@baffioso det er faktisk et emne, som jeg spekulerer lidt over i disse dage. Jeg har nemlig fået en anden henvendelse om præcis samme problematik.

Jeg håber, vi kan finde en løsning, som er så simpel mht GUI og brugeroplevelse, som muligt.

**Comment by baffioso** [comment]
Har lukket dette issue og flyttet det hen under [Konfiguration af søgeressourcer #16](https://github.com/Septima/qgis-geosearch/issues/16). Giver det mening?

**Comment by AsgerPetersen** [comment]
Yes. Den havde jeg overset
