### ISSUE TITLE
Tydeligere markering af fremsøgt adresse

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-geosearch#19]
Det lille røde kryds kan i et teknisk grundkort ofte være svær at få øje på. Hvis markeringen kunne blive tydeligere, fx en udfyldt firkant, cirkel eller noget andet, som man bedre kan få øje på. Farven rød synes jeg stadig er god at bruge til det formål.

**Comment by baffioso** [comment]
@Frederikssund Vil I være med til at finansiere denne forbedring?

**Comment by Frederikssund** [comment]
@baffioso - 
Septima har faktisk allerede forbedret udpegningen. Der bruges nu kun "røde kryds" ved markeringen af punkt baserede søgeobjekter (såsom adressepunkter o.lign). Øvrige markeringer er "røde rektangler" baseret på søgeobjekternes mbr. Hvad havde du tænkt dig med forbedringer ?

**Comment by baffioso** [comment]
@Frederikssund Vores byggesagsbehandlere vil gerne have at markeringen bliver større/tydeligere når de fremsøger en adresse. De har svært ved at finde krydset, hvis de f.eks. har luftfoto som baggrund.

**Comment by AsgerPetersen** [comment]
@baffioso @Frederikssund har I mulighed for at afprøve @JosefAssad s forslag, og se om det opfylder jeres behov?

**Comment by MieWinstrup** [comment]
@baffioso , @Frederikssund :

Som @JosefAssad foreslår kunne man lave en ny fane i indstillingsmenuen, hvor man kan specificere farve, linjebredde/punktstørrelse samt evt. form på visning af punkter (jeg forestiller mig at man kunne vælge mellem visning som punkt, kryds eller firkant omkring punktet).

Forslag til hvordan indstillingsdialogen kan se ud:
![geosearch_symbology](https://cloud.githubusercontent.com/assets/16276034/18340805/52739a68-75a7-11e6-83e4-1af26294af24.png)

Denne indstilling skal gemmes, så man bruger samme indstilling næste gang QGIS åbnes.

**Comment by Frederikssund** [comment]
#27 var lidt for "quick and dirty" ;-). Gav fejl når man brugte rubberband. Jeg har udviklet #28 , som eksponerer en række settings for rubberband og marker via Qgis menupunkt "Settings"->"Options"->"Advanced", setting "geosearch_dk". Dette giver mulighed for at tilrette rubberband og marker settings. Ændringer træder først i kraft efter genstart af Qgis.
Der er ikke udviklet nogen brugervenlig dialog til at opsætte disse værdier. Dette ville være et åbenlyst "næste skridt"

**Comment by AsgerPetersen** [comment]
Nu er https://github.com/Septima/qgis-geosearch/releases/tag/v0.2.7  releases/tag/v0.2.7  sendt til godkendelse. Bemærk, at de nye settings ikke dukker op i QGIS´ advanced settings før Geosearch's egen settings dialog har været åbnet og trykket OK.

Der er ændret i symboliseringen af de forskellige markører, hvilket muligvis vil genere nogle eksisterende brugere. Jeg håber, I vil være med til at hjælpe disse brugere.

**Comment by AsgerPetersen** [comment]
Bemærk, at der IKKE er lavet et brugervenligt GUI til at håndtere parametrene. Et sådant GUI kan naturligvis implementeres senere.
