### ISSUE TITLE
Lad bruger bestemme søgeressourcen ved indtastningen

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geosearch#2]
Skrives:

"adr: larsbj" søges kun i  "addresse" ressource.
"mat: 7a" søges kun i "matrikel" ressource.

And so on.

**Comment by baffioso** [comment]
Hej Asger, 

Ballerup Kommune vil gerne have en cirka pris på denne funktion. Du kan sende tilbudet til andb@balk.dk og ldg@balk.dk som CC.

Vh. Anders

**Comment by AsgerPetersen** [comment]
Det kunne måske være en ide, at kombinere dette med implementering af https://github.com/Septima/qgis-geosearch/issues/16#issue-112583251

I Settings-dialogen kan man se (og til/fravælge) søgeressourcer med fluen. Ud for hver søgeressource står desuden den 'text-shortcut', som kan bruges ved indtastning i søgeboksen.

**Comment by baffioso** [comment]
Super
