### ISSUE TITLE
Fix errorhandling when no searchresults are returned

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-geosearch#21]
When limiting the search to e.g. a municipality and searching for a municipality starting with 'p' no result is returned and the error is not handled correct. Need to be fixed.

**Comment by NicolaiMogensen** [comment]
Can reproduce. If searching for "adress" and entering ie. "njals" i get this error.

```
En fejl opstod under afviklingen af Python-kode:

Traceback (most recent call last):
  File "C:\ProgramData\.qgis2/python/plugins\geosearch_dk\autosuggest.py", line 171, in autoSuggest
    qurl = self.geturl_func( term )
  File "C:\ProgramData\.qgis2/python/plugins\geosearch_dk\searchbox.py", line 131, in geturl
    area=','.join(['muncode0'+str(k) for k in self.config['muncodes']])
TypeError: 'NoneType' object is not iterable

Python-version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS-version:
2.8.2-Wien Wien, 1b929ef
```

And after this, the plugin menu creates this error when trying to access it:

```
En fejl opstod under afviklingen af Python-kode:

Traceback (most recent call last):
  File "C:\ProgramData\.qgis2/python/plugins\geosearch_dk\searchbox.py", line 273, in show_settings_dialog
    dlg.kommunekoderLineEdit.setText(','.join(map(str, self.config['muncodes'])))
TypeError: argument 2 to map() must support iteration
```

I apologize if this error is already known, but this issue was the most related

**Comment by AsgerPetersen** [comment]
Hi @NicolaiMogensen,

Thank you for reporting this issue. Are you by any chance on a Linux system? If you are, I think it is a duplicate of #24

**Comment by NicolaiMogensen** [comment]
I am on windows 7

**Comment by NicolaiMogensen** [comment]
#24 looks a lot like the problem i'm experiencing, so perhaps it's not related to an error on Ubuntu?

**Comment by AsgerPetersen** [comment]
We haven't seen it in anything else than Ubuntu so far. But apparently it isn't unique to Ubuntu :-)

**Comment by bvthomsen** [comment]
@NicolaiMogensen , is your windows qgis setup using the -configpath qualifier - changing the settings from registry to an ini - file. I've experienced the same problem as you, when a Windows based QGIS is using an ini-file to store settings.
