### ISSUE TITLE
Network Error: Remote qlrSSL handshake failed

### ISSUE THREAD

**Issue by hsp** [Septima/qgis-geosearch#35]
I am having troubles using the QGIS (3) PlugIn 'Kortforsyningen' (2.4), on my Mac Running high Sierra, 10.13.4. 
I get all kinds of weird network connection errors.... and no maps :-)

**Comment by hsp** [comment]
And, by yhe way, my login/pwd works fine directly on kortforsyningen's homepage.
/H

**Comment by MieWinstrup** [comment]
Do you see the list of themes (i.e. 'Baggrundskort', 'Administrative Grænser' etc.)?

(this issue is related to the Kortforsyning Plugin and not Geosearch)

**Comment by hsp** [comment]
Hi Mie,

as matter of fact, I had problems on my Mac with both the QGIS2 and later the QGIS3 versions (on my Win machine it works perfectly).

  *   In QGIS2 it was kind of a network problem (qlrSSL handshake failed (#35)). The installer appeared to work.
  *   In QGIS3 the kortforsynings-installer fails. It resembles another classFactory-issue I found on github (#48). See the inserted error message below.

Cheers
Hans

--------------

Couldn't load plugin 'Kortforsyningen' due to an error when calling its classFactory() method

TypeError: 'QVariant' object is not subscriptable

Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/fjz687/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Kortforsyningen/__init__.py", line 35, in classFactory
    return Kortforsyningen(iface)
  File "/Users/fjz687/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Kortforsyningen/kortforsyningen.py", line 78, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
QGIS version: 3.0.2-Girona Girona, exported

Python Path:

  *   /Applications/QGIS3.app/Contents/MacOS/../Resources/python
  *   /Users/fjz687/Library/Application Support/QGIS/QGIS3/profiles/default/python
  *   /Users/fjz687/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
  *   /Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
  *   /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
  *   /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
  *   /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
  *   /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
  *   /Users/fjz687/Library/Application Support/QGIS/QGIS3/profiles/default/python

________________________________
Fra: Mie Winstrup [notifications@github.com]
Sendt: 13. maj 2018 22:28
Til: Septima/qgis-geosearch
Cc: Hans Skov-Petersen; Author
Emne: Re: [Septima/qgis-geosearch] Network Error: Remote qlrSSL handshake failed (#35)


Do you see the list of themes (i.e. 'Baggrundskort', 'Administrative Grænser' etc.)?

(this issue is related to the Kortforsyning Plugin and not Geosearch)

**Comment by AsgerPetersen** [comment]
Closing as the issue relates to https://github.com/Kortforsyningen/Qgis_plugin_Kortforsyningen_v3 and not this plugin.
