### ISSUE TITLE
Uncaught TypeError: can only concatenate str (not "NetworkError") to str


### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geosearch#47]
Steps to reproduce:

Not sure what type of network error it was. But I was just doing a regular search (typing into the search box) and boom!

```
Traceback (most recent call last):
  File "/Users/asger/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geosearch_dk/autosuggest.py", line 181, in handleNetworkData
    'Server returned: ' + reply.error(), __package__
TypeError: can only concatenate str (not "NetworkError") to str

```
geosearch_dk 1.2.0, QGIS 3.16.3-Hannover on Darwin 20.3.0

**Comment by andehass** [comment]
It can be fixed by replacing the standard token, provided with the plugin, with a new legit token to Dataforsyningen.

**Comment by AsgerPetersen** [comment]
Hi @andehass 

Yes, it looks like our default token wich is hard coded into the plugin has been invalidated. I am working on a new version of the plugin with a new token.

/Asger
