### ISSUE TITLE
SDFI nedlægger tjenesten `Geosearch`

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geosearch#50]
Septima har udviklet og vedligeholdt pluginet, siden vi publicerede første version af pluginet i maj 2013. Med årene er det blevet en naturlig del af mange danske QGIS-brugeres værktøjskasse.

SDFI har [annonceret](https://trello.com/c/URyuB8L6/177-opdatering-25012023-geosearch-lukker-31052023-anvend-i-stedet-gsearch), at de nedlægger søge-tjenesten `Geosearch` pr ~~31.05.2023~~ 31.08.2023 (Ny dato annonceret 24. april). Da QGIS Geosearch DK (dette plugin) benytter SDFIs tjeneste, betyder det, at pluginet må ændres for fortsat at kunne fungere.

SDFI har publiceret en ny tjeneste kaldet `gsearch`, som skulle erstatte `Geosearch`. Desværre er der så store ændringer i funktionsmåden mellem `Geosearch` og `GSearch`, at det er en både vanskelig og bekostelig affære at genskabe dele af pluginets funktionalitet med den nye service. Visse dele af funktionaliteten kan slet ikke genskabes.

Vi (i Septima) har været i god og hyppig dialog med SDFI om problematikken. En del af dialogen har foregået gennem issues på `Gsearch` GitHub repo:
- https://github.com/SDFIdk/gsearch/issues/180
- https://github.com/SDFIdk/gsearch/issues/179
- https://github.com/SDFIdk/gsearch/issues/185
- https://github.com/SDFIdk/gsearch/issues/186
- https://github.com/SDFIdk/gsearch/issues/187
- https://github.com/SDFIdk/gsearch/issues/188
- https://github.com/SDFIdk/gsearch/issues/189
- https://github.com/SDFIdk/gsearch/issues/190

Særligt https://github.com/SDFIdk/gsearch/issues/180 medfører en relativt omfattende (og dermed bekostelig) omskrivning  af koden i pluginet. Mens feks https://github.com/SDFIdk/gsearch/issues/179 betyder, at brugeroplevelsen for brugere der benytter filtrering på kommune vil blive stærkt forringet.

Vi har stor forståelse for, at Geosearch til QGIS kan være et vigtigt arbejdsredskab (Vi bruger det rigtig meget selv i Septima!). Derfor gik vi også straks i gang med at planægge opgraderingen til gsearch. Desværre har det jo vist sig, at forskellene på Geosearch og Gsearch er så store, at vi ikke kan afsætte de nødvendige ressourcer selv. 

Hvis der er nogen der ønsker at være med i delfinansiering, så skriv til mie@septima.dk.

For at gøre opgaven lidt mindre, kan der eventuelt laves en simplificeret udgave af pluginet, så der i det mindste kan søges i adresser når SDFI lukker `Geosearch`.

**Comment by kristianrl** [comment]
Kan det mon være lettere at anvende DAWA? https://dawadocs.dataforsyningen.dk/

**Comment by MieWinstrup** [comment]
Pluginet bruger Gsearch fra version 2.0.0 af pluginet. Dette issue lukkes.
