### ISSUE TITLE
Inkludér gerne en kopi af GPL-3.0-licensen i repositoriet

### ISSUE THREAD

**Issue by mikini** [Septima/qgis-geosearch#53]
Hejsa, tak for at vedligeholde og opdatere dette plugin.
Lige et par detaljer omkring licensering og GPL.

Det er god stil at hjælpe modtageren af kildekoden til et GPL-licenseret program med at overholde følgende del GPL's [afsnit 4](https://www.gnu.org/licenses/gpl-3.0.html#section4) ved at inkludere en kopi af licensen som en del kildekoden;

> "You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you [..] give all recipients a copy of this License along with the Program"

På denne måde har vedkommende overholdt dette ved blot at videreformidle det modtagne, og behøver ikke gøre yderligere ifht. at gøre opmærksom på programmets licens.

Dette gøres normalt ved at inkludere en fil kaldet COPYING i roden af repositoriet som indeholder ASCII-tekstudgaven af den relevante GPL-licens. Se mere om dette i [licensens "How to Apply These Terms"](https://www.gnu.org/licenses/gpl-3.0.html#howto)-afsnit eller [det tilsvarende afsnit i det separate "How to Use GNU Licenses"](https://www.gnu.org/licenses/gpl-howto.html#license-files)-dokument. Tekst-udgaver af licenserne kan findes ved at følge linket til den enkelte licens fra [FSF's licens-liste](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses), for GPL-3.0 er [det denne](https://www.gnu.org/licenses/gpl-3.0.txt).

Og igen god stil, men ikke påkrævet, et at [gøre slutbrugeren af programmet opmærksom på licensen og placere et link til denne i "About"-dialogen](https://www.gnu.org/licenses/gpl-howto.html#startup-notice) (altså her i teksten i [show_about_dialog()](https://github.com/Septima/qgis-geosearch/blob/44e5742fd675a53fa239124b1300c48a5b4e2476/src/geosearch_dk/searchbox.py#L261-L267), ([en](https://github.com/Septima/qgis-geosearch/blob/44e5742fd675a53fa239124b1300c48a5b4e2476/src/geosearch_dk/i18n/en.ts#L70))).

**Comment by AsgerPetersen** [comment]
Hej @mikini 

Tak for din udførlige beskrivelse. Grunden til at der ikke er en klar licens i dette repo er ganske enkelt, at det blev dannet med en plugin-template tilbage i 2013. Og der var licens-angivelsen åbenbart ikke en del af templaten. Vi i Septima har så fuldstændig overset, at den mangler. Den er med i vores andre qgis-plugins, som nok har brugt en senere version af templaten. Feks https://github.com/Septima/qgis-qlrbrowser/tree/master

Jeg tilføjer straks en licens til dette repo, så det er hævet over enhver tvivl.

I og med at alle QGIS-plugins skal overholde GPL (se feks https://blog.qgis.org/2016/05/29/licensing-requirements-for-qgis-plugins/), så tænker jeg, at det vil være overflødigt (og måske også lidt støjende), hvis hvert plugin ivrigt fortæller brugeren, at det er GPL.

Tak igen.

**Comment by AsgerPetersen** [comment]
Jeg har lagt GPL2 på. Jeg er ikke den store jurist, så jeg har kigget på, hvilken licens pluginet ville have haft, hvis den havde været inkluderet i templaten, og jeg har kigget på, hvilken licens QGIS er udgivet under (https://github.com/qgis/QGIS/blob/master/COPYING).

**Comment by mikini** [comment]
Ja, det er desværre tit en detalje der ikke er så meget fokus på. Jeg er heller ikke jurist, bare engageret tekniker ;). Det lyder lige til højrebenet at følge QGIS, især når plugin skal loades run-time i Python.

Mange bruger også varianten "or-later" så man automatisk tillader distribution under evt. fremtidige GPL-udgaver.
Dette er lidt snørklet, men forhindrer kompleksiteter over tid, når mange bidrager og man (som i; hvem end der er ansvarlig for projektet/forken på det tidspunkt) evt. gerne vil relicensere under en ny udgave af GPL (som ellers vil være nær umuligt).

Se mere om rationalet for dette i artiklen ["For Clarity's Sake, Please Don't Say “Licensed under GNU GPL 2”!"](https://www.gnu.org/licenses/identify-licenses-clearly.html). Humlen er at man bør være eksplicit i copyright-angivelsen i filheadere for om det udelukkende er den angivne licens man tillader ("-only"), eller om man også tillader fremtidige ("or-later").

Måske du her burde bruge "GPL-2.0-or-later", da readme hidtil har sagt "GPL3". Dette bør så også rettes til i readme så det matcher.

Reelt er det jo filheaderene der dikterer hvilken licens den enkelte fil er under (herunder også om det er only/later), så disse bør bestemt også matche.
De filer jeg lige har tjekket siger faktisk "GPL-3.0-or-later", så der er lidt mere arbejde hvia du vil have den ned på 2 (formelt juridisk er det nok et problem at gøre dette, da de tidligere udgaver jo VAR GPL3.0-or-later (og or-earlier findes ikke), men i praksis vil det nok ikke være et problem som mange af dine brugere går op i). Men kan se af artiklen at QGIS også er GPL-2.0-or-later, så det burde ikke give problemer at beholde den på "GPL-3.0-or-later" (uden at jeg lige har studeret QGIS eller plugin-mekanismen i detaljer).

PS: licensbenævnelserne er standardiseret i [SPDX-projektet](https://spdx.org/licenses/).

**Comment by AsgerPetersen** [comment]
Pyh. Jeg havde overset, at der var headers i filerne. Nu er COPYING opdateret til GPL3-or-later, så der der er konsistens. Tak for din vedholdenhed.
