### ISSUE TITLE
Mulighed for at søge med BFE

### ISSUE THREAD

**Issue by StineCasmoseChristiansen** [Septima/qgis-geosearch#60]
Det kunne være meget brugbart at kunne fremsøge en ejendom via BFE-nummer, og få vist de matrikler ejendommen indeholder.

**Comment by klavspc** [comment]
Hej Stine, Jeg forstår behovet, men GSearch, som pluginnet kalder, understøtter desværre ikke søgning på matrikelnumre med bfe
