### ISSUE TITLE
Tillad konfiguration i ini-fil i plugin-dir

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-geosearch#8]
På Windows gemmes pluginets konfiguration i registreringsdatabasen, hvilket i nogle tilfælde besværliggør udrulning.

Dette kan afhjælpes ved at pluginet checker, om der eksisterer en konfigurationsfil i plugin-dir. Hvis en sådan fil findes, benyttes den, i modsat fald benyttes defaultplacering.

**Comment by giovanniborella** [comment]
Især hvis dette gør det muligt at gemme ens login-oplysninger, så man ikke skal taste dem ind hver gang man genstarter Qgis [windows]

**Comment by AsgerPetersen** [comment]
Hej @giovanniborella betyder det, at du indtaster dit password hver gang du har haft QGIS lukket?

**Comment by giovanniborella** [comment]
@AsgerPetersen Ja. 
QGIS 2.14.0(startes med grass), windows 7

**Comment by AsgerPetersen** [comment]
@giovanniborella Det er virkelig underligt! Jeg har oprettet et seperat issue på dette (#25). Brugernavn og password skal selvfølgelig gemmes i konfigurationen. Der må være en bug.

**Comment by AsgerPetersen** [comment]
Med de nyere versioner af QGIS fungerer konfigurationen anderledes. Det oprindelige issue er derfor ikke relevant længere. Lukker.
